# Classification image using block based extracted features - 2class

In [3]:
import numpy as np
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import normalize
import pandas as pd

## Import data

#### Nikon

In [4]:
nikon=pd.read_csv("Final_dataset/Nikkon.csv")
nikon.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
0,129.580,118.910,112.390,1.1238,0.85779,0.78030,130.580,119.910,113.390,0.97634,0.97014,0.92186
1,128.710,117.570,110.410,1.1347,0.85198,0.76659,129.710,118.570,111.410,0.97886,0.97140,0.92855
2,138.440,131.440,127.320,1.0825,0.91245,0.87085,139.440,132.440,128.320,0.94940,0.94510,0.83543
3,131.140,124.000,119.160,1.0977,0.90811,0.85821,132.140,125.000,120.160,0.95199,0.93391,0.81582
4,75.374,67.811,63.859,1.1474,0.82397,0.75017,76.374,68.811,64.859,0.96298,0.96209,0.89646

In [5]:
# describe datset
nikon.describe()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
count,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000
mean,119.789661,112.493012,105.148195,188.418789,0.902765,0.908887,120.577139,113.302397,106.048200,0.916378,0.869106,0.861253
std,51.855566,50.396790,53.895270,2157.912339,0.290756,0.686864,51.774358,50.248531,53.732099,0.107428,0.150249,0.139179
min,6.651000,6.029600,6.728900,0.348730,0.103140,0.014781,7.651000,7.029600,8.131100,-0.321240,-0.084155,-0.114900
25%,79.845750,74.496250,63.010750,0.889603,0.732748,0.500323,80.558750,75.496250,63.803250,0.892135,0.810172,0.807955
50%,121.155000,113.385000,101.375000,1.019750,0.907375,0.849645,122.125000,114.105000,102.375000,0.955315,0.930415,0.903030
75%,157.947500,146.582500,147.182500,1.601425,0.999147,1.089175,158.022500,147.190000,148.182500,0.983270,0.968963,0.956803
max,246.070000,243.460000,254.970000,39798.000000,2.284600,5.572200,247.070000,244.460000,255.000000,0.998660,0.998450,0.996550

#### Canon

In [6]:
canon=pd.read_csv("Final_dataset/canon.csv")
canon.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
0,115.030,113.440,109.880,1.1214,0.96344,0.88919,116.040,114.440,110.880,0.98118,0.96749,0.95483
1,113.970,112.950,109.980,1.0959,0.97700,0.92073,114.980,113.950,110.990,0.98748,0.97684,0.96913
2,77.567,75.927,67.048,1.2820,0.97039,0.76680,78.567,76.927,68.048,0.96503,0.94548,0.88716
3,85.368,81.794,70.776,1.3348,0.92508,0.69720,86.368,82.794,71.776,0.97028,0.94772,0.89659
4,102.750,100.760,95.331,1.1660,0.96183,0.84911,103.770,101.760,96.360,0.98455,0.97259,0.95115

In [7]:
#describe data
canon.describe()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
count,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000
mean,103.728912,100.286369,87.964064,2.740439,1.023695,0.875187,104.452411,101.155351,88.956231,0.903484,0.874965,0.849052
std,53.370420,49.300251,47.916869,11.323551,0.297845,0.612265,53.131194,49.217431,47.884173,0.129092,0.151257,0.166506
min,3.634800,3.640300,3.516100,0.511580,0.200210,0.059322,4.744700,4.749600,4.646800,0.127170,0.270670,0.076699
25%,60.983750,62.395750,48.465500,1.012200,0.943488,0.590767,61.418250,63.396000,49.005000,0.879240,0.842033,0.792895
50%,100.443500,97.833000,81.550000,1.150150,1.019050,0.901000,101.435000,98.846000,82.565000,0.960440,0.940495,0.917920
75%,139.942500,131.900000,119.425000,1.807050,1.098550,1.029950,140.942500,132.900000,120.530000,0.983845,0.973015,0.961580
max,252.950000,238.250000,228.750000,226.780000,2.571200,4.869500,251.790000,233.350000,229.750000,0.999060,0.998060,0.996540

## Adding Class label

<ul>
<li>Canon : 0</li>
<li>Nikon : 1</li>

</ul>

In [8]:
nikon.loc[:,'label'] = pd.Series(1, index=nikon.index)
nikon.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,label
0,129.580,118.910,112.390,1.1238,0.85779,0.78030,130.580,119.910,113.390,0.97634,0.97014,0.92186,1
1,128.710,117.570,110.410,1.1347,0.85198,0.76659,129.710,118.570,111.410,0.97886,0.97140,0.92855,1
2,138.440,131.440,127.320,1.0825,0.91245,0.87085,139.440,132.440,128.320,0.94940,0.94510,0.83543,1
3,131.140,124.000,119.160,1.0977,0.90811,0.85821,132.140,125.000,120.160,0.95199,0.93391,0.81582,1
4,75.374,67.811,63.859,1.1474,0.82397,0.75017,76.374,68.811,64.859,0.96298,0.96209,0.89646,1

In [11]:
canon.loc[:,'label'] = pd.Series(0, index=canon.index)
canon.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,label
0,115.030,113.440,109.880,1.1214,0.96344,0.88919,116.040,114.440,110.880,0.98118,0.96749,0.95483,0
1,113.970,112.950,109.980,1.0959,0.97700,0.92073,114.980,113.950,110.990,0.98748,0.97684,0.96913,0
2,77.567,75.927,67.048,1.2820,0.97039,0.76680,78.567,76.927,68.048,0.96503,0.94548,0.88716,0
3,85.368,81.794,70.776,1.3348,0.92508,0.69720,86.368,82.794,71.776,0.97028,0.94772,0.89659,0
4,102.750,100.760,95.331,1.1660,0.96183,0.84911,103.770,101.760,96.360,0.98455,0.97259,0.95115,0

## Join Both data set & Normalise

In [12]:
data=pd.concat([canon,nikon])
data[595:605]

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,label
595,86.776,84.604,85.474,0.99215,0.94188,0.95522,87.805,85.619,86.482,0.99030,0.99257,0.98594,0
596,74.173,75.606,78.384,0.94069,1.03430,1.10520,75.173,76.606,79.384,0.98616,0.98447,0.97357,0
597,74.185,73.439,73.732,1.01700,0.97071,0.96811,75.185,74.439,74.732,0.97243,0.97394,0.95641,0
598,87.777,89.408,94.760,0.89921,1.02840,1.14940,88.777,90.408,95.760,0.99447,0.98998,0.98348,0
599,73.522,70.810,69.878,1.03020,0.92642,0.90046,74.522,71.810,70.878,0.99239,0.99347,0.98976,0
0,129.580,118.910,112.390,1.12380,0.85779,0.78030,130.580,119.910,113.390,0.97634,0.97014,0.92186,1
1,128.710,117.570,110.410,1.13470,0.85198,0.76659,129.710,118.570,111.410,0.97886,0.97140,0.92855,1
2,138.440,131.440,127.320,1.08250,0.91245,0.87085,139.440,132.440,128.320,0.94940,0.94510,0.83543,1
3,131.140,124.000,119.160,1.09770,0.90811,0.85821,132.140,125.000,120.160,0.95199,0.93391,0.81582,1
4,75.374,67.811,63.859,1.14740,0.82397,0.75017,76.374,68.811,64.859,0.96298,0.96209,0.89646,1

In [13]:
#select all coulomn except label #testing
data[1:3].loc[:,data.columns != 'label']

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
1,113.970,112.950,109.980,1.0959,0.97700,0.92073,114.980,113.950,110.990,0.98748,0.97684,0.96913
2,77.567,75.927,67.048,1.2820,0.97039,0.76680,78.567,76.927,68.048,0.96503,0.94548,0.88716

### Normalise

In [14]:
Norm_feature=normalize(data.loc[:,data.columns != 'label'], norm='l2', axis=1, copy=True)

In [15]:
Norm_feature

array([[ 0.41444219,  0.40871357,  0.39588723, ...,  0.0035351 ,
         0.00348577,  0.00344016],
       [ 0.41240425,  0.40871334,  0.3979663 , ...,  0.00357323,
         0.00353473,  0.00350683],
       [ 0.42696747,  0.41794009,  0.36906564, ...,  0.00531201,
         0.00520439,  0.00488337],
       ...,
       [ 0.54506468,  0.2833212 ,  0.34278007, ...,  0.00366319,
         0.0041919 ,  0.00381172],
       [ 0.61169925,  0.19638606,  0.28716062, ...,  0.00385838,
         0.00420217,  0.00398715],
       [ 0.58406712,  0.23121918,  0.31687219, ...,  0.00385711,
         0.00427447,  0.00401097]])

In [16]:
print(len(Norm_feature))

1176

# Create train and test

In [179]:
#concatenate numpy array

#training Set
train_x=Norm_feature[80:1100]
train_y=np.array(data[80:1100].loc[:,"label"])

#Testing Set
test_x=np.concatenate((Norm_feature[0:100], Norm_feature[1100:]), axis=0)
test_y=np.concatenate((np.array(data[0:100].loc[:,"label"]),np.array(data[1100:].loc[:,"label"])),axis=0)

# Classification

## SVM Classifier

In [180]:
# clsf = classifier
clsf=SVC(kernel='rbf',gamma=60,C=5) #SVM Classier
svm={} #store accuracy data for plotting

In [181]:
#training
clsf.fit(train_x, train_y)

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=60, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Testing accuracy on training data

In [182]:
#Now testing for trainig data
#Now predict values for given classifier
prediction = clsf.predict(train_x)
svm["trainig_set"]=accuracy_score(prediction,train_y)*100
print 'Accuracy Check ',svm["trainig_set"],'%'

Accuracy Check  84.3137254902 %

### Testing accuracy on Testing data

In [183]:
prediction = clsf.predict(test_x)
svm["test_set"]=accuracy_score(prediction,test_y)*100
print 'Accuracy Check ',svm["test_set"],'%'

Accuracy Check  76.7045454545 %

In [184]:
svm

{'test_set': 76.704545454545453, 'trainig_set': 84.313725490196077}

## Decision Tree Classifier

In [212]:
decision={}
clf=DecisionTreeClassifier(max_depth=50,min_samples_split=12)
clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=50,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=12, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [213]:
#train
clf = clf.fit(train_x, train_y)

### Testing accuracy on training data

In [214]:
#Now testing for trainig data
#Now predict values for given classifier
prediction = clf.predict(train_x)
decision["trainig_set"]=accuracy_score(prediction,train_y)*100
print 'Accuracy Check ',decision["trainig_set"],'%'

Accuracy Check  95.5882352941 %

### Testing accuracy on Testing data

In [215]:
prediction = clf.predict(test_x)
decision["test_set"]=accuracy_score(prediction,test_y)*100
print 'Accuracy Check ',decision["test_set"],'%'

Accuracy Check  76.7045454545 %

In [216]:
decision

{'test_set': 76.704545454545453, 'trainig_set': 95.588235294117652}

In [177]:
for i in range(len(test_x)):
    print i,prediction[i]

0 1
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 1
16 0
17 0
18 0
19 0
20 0
21 0
22 0
23 0
24 0
25 0
26 1
27 1
28 0
29 0
30 0
31 0
32 0
33 0
34 0
35 0
36 1
37 0
38 1
39 1
40 0
41 0
42 0
43 0
44 1
45 0
46 1
47 0
48 0
49 1
50 0
51 0
52 1
53 1
54 0
55 1
56 1
57 0
58 1
59 0
60 0
61 1
62 0
63 1
64 1
65 0
66 0
67 1
68 0
69 0
70 1
71 0
72 0
73 0
74 0
75 0
76 0
77 0
78 0
79 0
80 0
81 0
82 0
83 1
84 0
85 0
86 0
87 0
88 0
89 0
90 0
91 0
92 0
93 0
94 0
95 0
96 0
97 1
98 1
99 1
100 1
101 1
102 1
103 1
104 1
105 1
106 0
107 1
108 0
109 1
110 0
111 1
112 1
113 1
114 1
115 1
116 1
117 1
118 1
119 1
120 1
121 1
122 1
123 1
124 1
125 1
126 1
127 1
128 1
129 1
130 1
131 1
132 1
133 1
134 1
135 1
136 1
137 1
138 1
139 1
140 0
141 0
142 1
143 0
144 1
145 1
146 0
147 1
148 0
149 1
150 1
151 0
152 0
153 1
154 1
155 1
156 1
157 0
158 1
159 0
160 0
161 1
162 0
163 0
164 0
165 1
166 0
167 0
168 1
169 1
170 0
171 1
172 1
173 1
174 1
175 1

## Neural Net Classifier

In [2]:
from sklearn.neural_network import MLPClassifier

ImportError: cannot import name MLPClassifier

In [ ]:
neural=dict()
clf = MLPClassifier(algorithm='l-bfgs',hidden_layer_sizes=(50,), alpha=1e-5, random_state=1)
clf

In [ ]:
#trainig Network
clf.fit(train_x, train_y)

### Testing accuracy on training data

In [ ]:
#Now testing for trainig data
#Now predict values for given classifier
prediction = clf.predict(train_x)
neural["trainig_set"]=accuracy_score(prediction,train_y)*100
print 'Accuracy Check ',neural["trainig_set"],'%'

### Testing accuracy on testing data

In [ ]:
prediction = clf.predict(test_x)
neural["test_set"]=accuracy_score(prediction,test_y)*100
print 'Accuracy Check ',neural["test_set"],'%'

In [ ]:
neural

## Ploting

In [ ]:
import pylab as plt
plt.rcParams['figure.figsize'] = 16, 12

In [ ]:
#%pylab inline
classifier = [1,2,3,4]
accuracy_test_data=[svm["test_set"],decision["test_set"],kmean["test_set"],neural["test_set"]]
LABELS=["SVM","Decision-Tree","K-Mean","Neural-net"]

plt.bar(classifier,accuracy_test_data,align='center')
plt.xticks(classifier, LABELS) #binding label with x axis data
plt.xlabel('Classifier')
plt.ylabel('Accuracy')
plt.title('Analysis with 2 Class')
plt.show()